export const LogoInfo = [
{
    id: 1,
    level: 1,
    name: 'Rocky',
    url: '/fotos/0001.jpg',
    done: false,
    hint: 'R_ _ _y',
    hintIsOpen: false,
    possibleAnswer: ['rocky', 'rocky balboa', 'balboa'],
    category: 'Tv and Movies'
},
{
    id: 2,
    level: 1,
    name: 'Harry Potter',
    url: '/fotos/0002.jpg',
    done: false,
    hint: 'H_ _ _y P_ _ _ _r',
    hintIsOpen: false,
    possibleAnswer: ['harry potter', 'harry', 'potter'],
    category: 'Tv and Movies'
},
{
    id: 3,
    level: 2,
    name: 'The Matrix',
    url: '/fotos/0003.jpg',
    done: false,
    hint: 'T_ _ M_ _ _ _x',
    hintIsOpen: false,
    possibleAnswer: ['the matrix', 'matrix'],
    category: 'Tv and Movies'
},
{
    id: 4,
    level: 1,
    name: 'Star Wars',
    url: '/fotos/0004.jpg',
    done: false,
    hint: 'S_ _ _ W_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['star wars', 'star war'],
    category: 'Tv and Movies'
},
{
    id: 5,
    level: 2,
    name: 'Green Book',
    url: '/fotos/0005.jpg',
    done: false,
    hint: 'G_ _ _n B_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['green book'],
    category: 'Tv and Movies'
},
{
    id: 6,
    level: 2,
    name: 'Fight Club',
    url: '/fotos/0006.jpg',
    done: false,
    hint: 'F_ _ _t C_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['fight club'],
    category: 'Tv and Movies'
},
{
    id: 7,
    level: 2,
    name: 'Gladiator',
    url: '/fotos/0007.jpg',
    done: false,
    hint: 'G_ _d_ _ _ _r',
    hintIsOpen: false,
    possibleAnswer: ['gladiator'],
    category: 'Tv and Movies'
},
{
    id: 8,
    level: 1,
    name: 'Troy',
    url: '/fotos/0008.jpeg',
    done: false,
    hint: 'T_ _y',
    hintIsOpen: false,
    possibleAnswer: ['troy'],
    category: 'Tv and Movies'
},
{
    id: 9,
    level: 3,
    name: 'Gollum',
    url: '/fotos/0009.jpeg',
    done: false,
    hint: 'G_ _ _ _m',
    hintIsOpen: false,
    possibleAnswer: ['smeagol', 'gollum'],
    category: 'Character'
},
{
    id: 10,
    level: 1,
    name: 'Terminator',
    url: '/fotos/0010.jpeg',
    done: false,
    hint: 'T_ _ _ _ _ _ _ _r',
    hintIsOpen: false,
    possibleAnswer: ['terminator'],
    category: 'Tv and Movies'
},
{
    id: 11,
    level: 1,
    name: 'Steve Jobs',
    url: '/fotos/0011.jpeg',
    done: false,
    hint: 'S_ _ _ _ J_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['steve jobs', 'jobs', 'steve'],
    category: 'People'
},
{
    id: 12,
    level: 1,
    name: 'Shrek',
    url: '/fotos/0012.jpg',
    done: false,
    hint: 'S_ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['shrek'],
    category: 'TV and Movies'
},
{
    id: 13,
    level: 2,
    name: 'Salvador Dali',
    url: '/fotos/0013.jpeg',
    done: false,
    hint: 'S_ _ _ _ _ _ _ D_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['salvador dali', 'dali'],
    category: 'People'
},
{
    id: 14,
    level: 2,
    name: 'The Big Bang Theory',
    url: '/fotos/0014.png',
    done: false,
    hint: 'T_ _ B_ _ B_ _ _ T_ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['the big bang theory', 'tbbt'],
    category: 'Tv and Movies'
},
{
    id: 15,
    level: 1,
    name: 'Avatar',
    url: '/fotos/0015.jpeg',
    done: false,
    hint: 'A_ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['avatar'],
    category: 'Tv and Movies'
},
{
    id: 16,
    level: 1,
    name: 'Luffy',
    url: '/fotos/0016.jpeg',
    done: false,
    hint: 'L_ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['luffy', 'monkey', 'monkey d luffy'],
    category: 'Character'
},
{
    id: 17,
    level: 2,
    name: 'Roronoa Zoro',
    url: '/fotos/0017.jpeg',
    done: false,
    hint: '_ _r_',
    hintIsOpen: false,
    possibleAnswer: ['zoro', 'roronoa', 'roronoa zoro'],
    category: 'Character'
},
{
    id: 18,
    level: 3,
    name: 'Jack Sparrow',
    url: '/fotos/0018.jpeg',
    done: false,
    hint: 'J_ _ _ S_ _ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['jack', 'sparrow', 'jack sparrow', 'captain jack sparrow'],
    category: 'Character'
},
{
    id: 19,
    level: 3,
    name: 'Forrest Gump',
    url: '/fotos/0019.jpeg',
    done: false,
    hint: 'F_ _ _ _ _ _ G_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['forrest', 'gump', 'forrest gump'],
    category: 'Character'
},
{
    id: 20,
    level: 3,
    name: 'Saitama',
    url: '/fotos/0020.jpeg',
    done: false,
    hint: 'S_ _ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['saitama', 'saitama sensei'],
    category: 'Character'
},
{
    id: 21,
    level: 3,
    name: 'Kratos',
    url: '/fotos/0021.jpeg',
    done: false,
    hint: 'K_ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['kratos'],
    category: 'Character'
},
{
    id: 22,
    level: 1,
    name: 'Game Of Thrones',
    url: '/fotos/0022.jpeg',
    done: false,
    hint: 'G_ _ _ O_ T_ _ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['game of thrones', 'got'],
    category: 'Tv and Movies'
},
{
    id: 23,
    level: 2,
    name: 'John Snow',
    url: '/fotos/0023.jpeg',
    done: false,
    hint: 'J_ _ _ S_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['john snow', 'snow', 'john'],
    category: 'Character'
},
{
    id: 24,
    level: 2,
    name: 'Walter White',
    url: '/fotos/0024.png',
    done: false,
    hint: 'W_ _ _ _ _ W_ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['walter', 'white', 'walter white', 'heisenberg'],
    category: 'Character'
},
{
    id: 25,
    level: 2,
    name: 'Yoda',
    url: '/fotos/0025.jpeg',
    done: false,
    hint: '_ _d_',
    hintIsOpen: false,
    possibleAnswer: ['yoda'],
    category: 'Character'
},
{
    id: 26,
    level: 3,
    name: 'Python',
    url: '/fotos/0026.png',
    done: false,
    hint: 'P_ _h_ _',
    hintIsOpen: false,
    possibleAnswer: ['python'],
    category: 'Brand'
},
{
    id: 27,
    level: 3,
    name: 'Visual Studio',
    url: '/fotos/0027.png',
    done: false,
    hint: 'V_ _ _ _ _ S_ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['visual studio', 'microsoft visual studio', 'vs'],
    category: 'Brand'
},
{
    id: 28,
    level: 3,
    name: 'Hannibal Lecter',
    url: '/fotos/0028.jpeg',
    done: false,
    hint: 'H_ _ _ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['hannibal', 'lecter', 'hannibal lecter'],
    category: 'Character'
},
{
    id: 29,
    level: 3,
    name: 'Thanos',
    url: '/fotos/0029.jpg',
    done: false,
    hint: 'T_ _ _ _s',
    hintIsOpen: false,
    possibleAnswer: ['thanos'],
    category: 'Character'
},
{
    id: 30,
    level: 3,
    name: 'Isaac Newton',
    url: '/fotos/0030.jpg',
    done: false,
    hint: 'I_ _ _ _ N_ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['isaac newton', 'newton', 'isaac'],
    category: 'People'
},
{
    id: 31,
    level: 4,
    name: 'Thor',
    url: '/fotos/0031.jpg',
    done: false,
    hint: '_ _o_',
    hintIsOpen: false,
    possibleAnswer: ['thor'],
    category: 'Character'
},
{
    id: 32,
    level: 4,
    name: 'Nikola Tesla',
    url: '/fotos/0032.jpg',
    done: false,
    hint: 'N_ _ _ _ _ T_ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['tesla', 'nikola', 'nikola tesla', 'nichola tesla'],
    category: 'People'
},
{
    id: 33,
    level: 4,
    name: 'Peter Pan',
    url: '/fotos/0033.jpg',
    done: false,
    hint: 'P_ _ _ _ P_ _',
    hintIsOpen: false,
    possibleAnswer: ['peter pan', 'pan', 'peter'],
    category: 'Character'
},
{
    id: 34,
    level: 4,
    name: 'Mrs. Doubtfire',
    url: '/fotos/0034.jpg',
    done: false,
    hint: 'M_ _. D_ _ _t_ _ _e',
    hintIsOpen: false,
    possibleAnswer: ['mrs. doubtfire', 'doubtfire'],
    category: 'Tv and Movies'
},
{
    id: 35,
    level: 4,
    name: 'Graham Bell',
    url: '/fotos/0035.jpg',
    done: false,
    hint: 'G_ _ _ _m B_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['alexander graham bell', 'graham bell', 'bell', 'alexander'],
    category: 'People'
},
{
    id: 36,
    level: 4,
    name: 'Dirty Dancing',
    url: '/fotos/0036.jpg',
    done: false,
    hint: 'D_ _ _ _ D_ _ _i_ _',
    hintIsOpen: false,
    possibleAnswer: ['dirty dancing'],
    category: 'Tv and Movies'
},
{
    id: 37,
    level: 4,
    name: 'Edison',
    url: '/fotos/0037.jpg',
    done: false,
    hint: 'E_ _ _ _ _',
    hintIsOpen: false,
    possibleAnswer: ['edison', 'thomas edison', 'thomas alba edison'],
    category: 'People'
},
{
    id: 38,
    level: 4,
    name: 'Sherlock Holmes',
    url: '/fotos/0038.jpeg',
    done: false,
    hint: 'S_ _r_ _c_',
    hintIsOpen: false,
    possibleAnswer: ['sherlock', 'holmes', 'sherlock holmes'],
    category: 'Character'
},
{
    id: 39,
    level: 4,
    name: 'Da Vinci',
    url: '/fotos/0039.jpeg',
    done: false,
    hint: 'D_v_ _ _',
    hintIsOpen: false,
    possibleAnswer: ['davinci', 'da vinci', 'leonardo', 'leonardo davinci'],
    category: 'People'
},
{
    id: 40,
    level: 4,
    name: 'Jason',
    url: '/fotos/0040.jpeg',
    done: false,
    hint: '_ _s_ _',
    hintIsOpen: false,
    possibleAnswer: ['jason'],
    category: 'Character'
},

]